version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12  # Specify the runtime version if needed
    commands:
      - echo Installing Terraform
      - wget https://releases.hashicorp.com/terraform/1.9.5/terraform_1.9.5_linux_amd64.zip
      - unzip terraform_1.9.5_linux_amd64.zip
      - mv terraform /usr/local/bin/
      - terraform --version

  pre_build:
    commands:
      - echo Initializing Terraform
      - cd ${CODEBUILD_SRC_DIR}/
      - terraform init

  build:
    commands:
      - echo Validating Terraform configuration
      - terraform validate
      - echo Planning Terraform changes
      - terraform plan -out=tfplan

  post_build:
    commands:
      - echo Applying Terraform changes
      - terraform apply -auto-approve tfplan

artifacts:
  files:
    - '**/*'
  discard-paths: yes

cache:
  paths:
    - /root/.terraform
    - /root/.terraform.d
    - /root/.local/share/terraform